version: '3.8'
services:
  app:
    build: .
    environment:
      # App-related environment variables
      APP_LOG_LEVEL: INFO
      APP_PORT: 8000
      APP_HOST: localhost
      APP_NAME: algo-trading
      APP_VERSION: 1.0.0

      # MongoDB-related environment variables
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: test
      DB_USERNAME: root
      DB_PASSWORD: password

      # Redis-related environment variables
      CACHE_HOST: redis
      CACHE_PORT: 6379
      CACHE_DB: 0

      # Kafka-related environment variables
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # Binance-related environment variables
      BINANCE_API_KEY:
      BINANCE_SECRET_KEY:
      BINANCE_WEBSOCKET_STREAM: wss://stream.testnet.binance.vision:9443/ws/

      # Contact-related environment variables
      ADMIN_EMAIL: mcdemirer@gmail.com
      ADMIN_NAME: Çağdaş Demirer

    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb
      - redis
      - kafka
    restart: on-failure

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    restart: on-failure

  redis:
    image: redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "6379:6379"
    restart: on-failure

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENER: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_INTERFACE: PLAINTEXT
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: on-failure

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    restart: on-failure
